---
title: "Class 05"
author: "Ethan Vukovic"
date: "2026-09-09"
output: 
  html_document:
    toc: true
    foc_float: true
    numbered_sections: true
    code_folding: show
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Game 01: Find your seat

```{r game01}
campus = jsonlite::fromJSON(
  "https://isa401-find-your-seat.vercel.app/campus.json")

dplyr::glimpse(campus)

fsb = campus[['Farmer']]
fsb$code

fsb[["floors"]][["2"]]$sections

fsb[["floors"]][["2"]][["rooms"]]

```

```{r read_excel}
occupation = readxl::read_excel(
  path = "data/occupation.xlsx", sheet = "Table 1.4", skip = 1)

# optional: clean the bottom three rows
occupation = occupation[-c(32,33,34),] # Delete three specific rows, keep all cols
``` 

logins = readr::read_csv("https://isa401-import-heist.vercel.app/api/stage1")


log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=smithj31")

stage2 = log$events

jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/finish?code=6")








